#!/bin/bash

echo "Please enter the username of the user"
echo -e "account you wish to delete from system: \c"






选项中加入 -e ，可在输出文字中插入转义字符

转义字符如下：

　　　　　　\a 发出警告声；

　　　　　　\b 删除前一个字符；

　　　　　　\c 最后不加上换行符号；

　　　　　　\n 换行且光标移至行首；

　　　　　　\r 光标移至行首，但不换行；

　　　　　　\v 与\f相同；

　　　　　　\\ 插入\字符；

　　　　　　\0nn 插入0nn（八进制）代表的ASCII；
